### PR TITLE
update to Verify beta

### PR DESCRIPTION
**Pull request by SimonCropp**
handle this change https://github.com/VerifyTests/Verify/pull/646

### CODE REVIEW

**Comment by patriksvensson** [comment]
@SimonCropp Happy to merge this, but would need the checks to pass for it.

**Comment by patriksvensson** [comment]
@SimonCropp I have some spare time, so I'll do it.

**Comment by patriksvensson** [comment]
@SimonCropp Actually, I'll wait until 18.0.0 has been released. Want the version number of this project to follow Verify.

**Comment by SimonCropp** [comment]
yep. no worries. i will re submit when it is stable

**Pull request closed without merging**
